### ISSUE TITLE
JSON Encoding for POST requests

### ISSUE THREAD

**Issue by annca** [cuba/NetworkKit#1]
https://github.com/cuba/NetworkKit/blob/23cbafe9801f1086a75f3ebf53abd07f4c798eca/Source/NetworkDispatcher.swift#L164

When making a `POST` request with a JSON body, I had to change the encoding on this line to `JSONEncoding.default` to get it to work. Otherwise I kept getting an "invalid request" response. Don't know what the proper solution would be. Maybe need to add some logic to configure the encoding based on method or something?

**Comment by cuba** [comment]
Fixed!

I'll try to add some better tests for POST requests in my example file. Unfortunately there is no real good way to add unit tests for HTTP requests.
